[package]
name = "discogs-rust"
version = "0.1.0"
authors = ["riksolo <mail@riksolo.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
serde = {version = "*", features = ["derive"]}
serde_json = "*"
serde_derive = ""
lazy_static = "1.3.0"